export const injectedSnippetsList = [
  "abort-current-inline-script",
  "abort-on-iframe-property-read",
  "abort-on-iframe-property-write",
  "abort-on-property-read",
  "abort-on-property-write",
  "cookie-remover",
  "debug",
  "freeze-element",
  "hide-if-shadow-contains",
  "json-override",
  "json-prune",
  "override-property-read",
  "prevent-listener",
  "strip-fetch-query-parameter",
  "trace",
];
